name: Blank issue
description: Use this template if none of the other templates fit
title: ''
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Use this template if your issue does not fit into bug reports or feature requests.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clearly describe the issue, idea, or question.
      placeholder: What are you trying to do?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: false

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What actually happened?
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Steps to reproduce the issue (if applicable).
      placeholder: |
        1. …
        2. …
        3. …
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### Environment (fill in what's relevant)

  - type: input
    id: lib_version
    attributes:
      label: Library version
      placeholder: e.g. 0.1.9

  - type: input
    id: rn_version
    attributes:
      label: React Native version
      placeholder: e.g. 0.73.4

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Android
        - iOS
        - Both
        - Not sure

  - type: input
    id: device
    attributes:
      label: Device / Emulator
      placeholder: Pixel 7 / iPhone 14 / Emulator

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Logs, screenshots, videos, or anything else useful.
