name: 'Feature Suggestion'
description: 'Suggest a new feature to improve our library.'
title: 'feature request: '
labels: ['🎉 feature']
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for suggesting a new feature for our library!
        Please provide as much detail as possible below so we can evaluate your idea.

  - type: textarea
    id: feature-description
    attributes:
      label: 'Feature Description'
      description: 'A clear and concise description of the proposed feature.'
      placeholder: 'Describe the feature you are proposing...'
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 'Motivation and Use Case'
      description: 'Explain why this feature would improve the mobile experience and describe any specific use cases or issues it addresses.'
      placeholder: 'Explain the benefits and use case for the feature...'
    validations:
      required: true

  - type: textarea
    id: implementation-ideas
    attributes:
      label: 'Implementation Ideas'
      description: 'Share any thoughts on how this feature might be implemented.'
      placeholder: 'Share your ideas or potential solutions...'
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 'Additional Context'
      description: 'Any additional information or context to help us better understand your suggestion.'
